[tool.flake8]
ignore = ['E231', 'E241']
per-file-ignores = [
    '__init__.py:F401',
]
max-line-length = 120
count = true


#[tool.pytest.ini_options]
#minversion = "6.0"
#addopts = "--no-header -ra -v" # -s for pringing in tests
#testpaths = [
#    "tests",
#]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov --cov-report xml --cov-report term-missing"
testpaths = ["tests"]
pythonpath = ["src"]
filterwarnings = ["ignore::DeprecationWarning"]
markers = [
    "integration"
]
norecursedirs = ["src/authentifield/model_template/auto_AD/"]

[tool.coverage]
    [tool.coverage.run]
    omit = [
        # omit anything in a .local directory anywhere
        '__init__.py',
        'tests/*',
        '*/tests/*',
        # omit anything in a .venv directory anywhere
        '.venv/*'
    ]

    [tool.coverage.report]
    skip_empty = true

[tool.isort]
profile = "black"

[tool.black]
line-length = 120